# Generated by Django 2.2 on 2020-12-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eduSystem.Subject'),
            preserve_default=False,
        ),
    ]
