# Generated by Django 2.2 on 2020-12-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduSystem', '0015_auto_20201211_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
