# Generated by Django 2.2 on 2020-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduSystem', '0017_auto_20201211_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teacher_subject', to='eduSystem.Subject'),
        ),
    ]
